### ISSUE TITLE
New topogical map editor

### ISSUE THREAD

**Issue by Jailander** [LCAS/topological_navigation#108]
We need to make an easy way of editing the topological map that doesn't require any running components but allows us to edit all properties in the map file [new format here](https://github.com/LCAS/topological_navigation/issues/35).

**Comment by Jailander** [comment]
List of requirements:
Check this for inspiration https://github.com/LCAS/RASberry/blob/master/rasberry_topological_utils/scripts/topological_map_editor.py

* Simplify running it, right now to run the sytem you need to give the path to the map file, the datum file, the topological map file, and set output file name from the start, for exaple:
```
usage: topological_map_editor.py [-h] [--map MAP] [--tmap TMAP]
                                 [--empty EMPTY] [--outmap OUTMAP]
                                 [--outpointset OUTPOINTSET] [--datum DATUM]
                                 [--zoom ZOOM]
```
The idea would be to run the editor and then be able to load either a folder or each file individually.

* Be able to edit images with or without satellite images (i.e. no datum file), which means loading 2d maps directly on the canvas
* Ability to edit all the fields

**Comment by Iranaphor** [comment]
Closing as stale.
