### ISSUE TITLE
pip dependency

### ISSUE THREAD

**Issue by marc-hanheide** [LCAS/topological_navigation#173]
We should avoid pip dependencies, to facilitate releases of `.deb` packages. I just found 

https://github.com/LCAS/topological_navigation/blob/a2a1a775cbe57f72c3f73d8032b0c4edc3de1c47/topological_navigation/package.xml#L35

@Iranaphor is this required or can it be removed (blame shows you added it)?

In general, please everybody in @LCAS/aoc_devs avoid pip dependencies as much as possible. If there are any needed, let me know and we discuss ooptions.

**Comment by Iranaphor** [comment]
It is used for conversion between quarternion and euler with `from tf_transformations import quaternion_from_euler`. In ROS1, this functionality was achieved through `tf.transformations.quaternion_from_euler`.

---
All the locations in which this functionality is required are listed below:

policy_marker2.py:9:
from tf_transformations import quaternion_from_euler

policy_marker2.py:88:
qat = quaternion_from_euler(0, 0, angle)

policy_marker.py:9:
from tf_transformations import quaternion_from_euler

policy_marker.py:82:
qat = quaternion_from_euler(0, 0, angle)

edge_controller.py:107:
qat = tf.transformations.quaternion_from_euler(0, 0, angle)

policies.py:97:
qat = tf.transformations.quaternion_from_euler(0, 0, angle)

edge_std.py:86:
qat = tf.transformations.quaternion_from_euler(0, 0, angle)

scenario_server.py:193:
return (trans.euler_from_quaternion(q1)[2] - trans.euler_from_quaternion(q2)[2]) * 180/np.pi

**Comment by Iranaphor** [comment]
I think this was included in error.

**Comment by marc-hanheide** [comment]
so, can you make PR to remove?

**Comment by Iranaphor** [comment]
CI in progress for #174
