### ISSUE TITLE
Test keeps failing 

### ISSUE THREAD

**Issue by marc-hanheide** [LCAS/topological_navigation#194]
The test fails apparently randomly, e.g. https://github.com/LCAS/topological_navigation/actions/runs/11192495126/job/31116712588

please investigate and fix

**Comment by ibrahimhroob** [comment]
Roger

**Comment by marc-hanheide** [comment]
Flagging this up again

**Comment by ibrahimhroob** [comment]
I did increase the test timeout, it seems to work
