### ISSUE TITLE
get closest edge to robot

### ISSUE THREAD

**Issue by Jailander** [LCAS/topological_navigation#24]
Functions useful for this 
https://github.com/SAGARobotics/AgriNav/blob/master/polytunnel_navigation_actions/scripts/in_row_trav.py#L512-L524
https://github.com/SAGARobotics/AgriNav/blob/master/polytunnel_navigation_actions/scripts/in_row_trav.py#L464-L476

**Comment by adambinch** [comment]
Done with this function https://github.com/LCAS/topological_navigation/blob/2283bf44707b24b7e7b9cd07bc1aaca0a1fec4f3/topological_navigation/scripts/localisation.py#L165
