### ISSUE TITLE
Topological map manager update

### ISSUE THREAD

**Issue by Jailander** [LCAS/topological_navigation#34]
The topological map manager needs to be able to work with the new map format and provide the same services as it did in the previous versions. it should also:

- [x] Ensure Backwards compatibility by converting old map types into the new format (#35 )
- [x] Work from Files and MongoDB store
- [x] All manager services available and working on new map type

**Comment by Jailander** [comment]
- [ ] All manager services available and working on new map type

**Comment by adambinch** [comment]
This is sorted now so will close
