### ISSUE TITLE
Toponav 2 issue: Mapping from the pose field in the tmap to a ROS msg

### ISSUE THREAD

**Issue by adambinch** [LCAS/topological_navigation#74]
In toponav 2 we want to be able to use any type of goals (not just move base type). Therefore in the new map format, for an edge, there is a new `goal` field which sets the args (e.g. `target_pose`) for the goal. Toponav 2 will allow you to pass properties of the node to the goal like this
 
```yaml
    goal:
      target_pose: $node.pose
```

However, the target pose required by most goals seems to be of `geometry_msgs/PoseStamped` type, where as the pose in the tmap maps to a `geometry_msgs/Pose` msg. To avoid hard coding this mapping, we could use a new arg in the tmap

```yaml
pose_msg: `geometry_msgs/PoseStamped`
```

**Comment by Jailander** [comment]
or even better do something like this:
```yaml
target_pose:
  pose: $node.pose
```

**Comment by adambinch** [comment]
Yep went for your suggestion @Jailander . Done.
